spring:
  application:
    name: company

#  datasource:
#    url: jdbc:mysql://localhost:3306/msa_order
#    username: root
#    password: Gusdk5540!
#    driver-class-name: com.postgres.
#  jpa:
#    show-sql: true
#    database: mysql
#    hibernate:
#      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19093