spring:
  application:
    name: eureka


  datasource:
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:test_db;
    username: testdb
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
server:
  port: 19090